-- MySQL Script generated by MySQL Workbench
-- Thu Aug  9 16:10:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema virginia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema virginia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `virginia` DEFAULT CHARACTER SET utf8 ;
USE `virginia` ;

-- -----------------------------------------------------
-- Table `virginia`.`billing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virginia`.`billing` (
  `billing_id` INT NOT NULL AUTO_INCREMENT,
  `billing_price` BIGINT(11) NOT NULL,
  `billing_name` VARCHAR(225) NOT NULL,
  `billing_quantity` BIGINT(11) NOT NULL,
  `reservation_key` TEXT NOT NULL,
  PRIMARY KEY (`billing_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virginia`.`guest`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virginia`.`guest` (
  `guest_id` INT NOT NULL AUTO_INCREMENT,
  `guest_firstname` VARCHAR(45) NOT NULL,
  `guest_lastname` VARCHAR(45) NOT NULL,
  `guest_gender` VARCHAR(10) NOT NULL,
  `guest_phone` BIGINT(11) NOT NULL,
  `guest_address` TEXT NOT NULL,
  `guest_email` TEXT NOT NULL,
  PRIMARY KEY (`guest_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virginia`.`room_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virginia`.`room_type` (
  `room_type_id` INT NOT NULL AUTO_INCREMENT,
  `room_type_name` VARCHAR(255) NOT NULL,
  `room_type_description` TEXT NOT NULL,
  `room_type_pax` INT(10) NOT NULL,
  `room_type_image` VARCHAR(225) NOT NULL,
  `room_type_price` BIGINT(11) NOT NULL,
  PRIMARY KEY (`room_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virginia`.`reservation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virginia`.`reservation` (
  `reservation_id` INT NOT NULL AUTO_INCREMENT,
  `reservation_in` BIGINT(11) NOT NULL,
  `reservation_out` BIGINT(11) NOT NULL,
  `reservation_adult` BIGINT(11) NOT NULL,
  `reservation_child` BIGINT(11) NOT NULL,
  `reservation_roomCount` BIGINT(11) NOT NULL,
  `reservation_day_type` BIGINT(11) NOT NULL,
  `reservation_status` BIGINT(11) NOT NULL,
  `reservation_key` VARCHAR(255) NOT NULL,
  `reservation_reserved_at` BIGINT(15) NOT NULL,
  `reservation_updated_at` BIGINT(15) NOT NULL,
  `reservation_payment_status` TINYINT(1) NOT NULL,
  `reservation_payment_photo` TEXT NOT NULL,
  `reservation_requests` TEXT NULL,
  `guest_id` INT NOT NULL,
  `room_type_id` INT NOT NULL,
  PRIMARY KEY (`reservation_id`),
  INDEX `fk_reservation_guest1_idx` (`guest_id` ASC) VISIBLE,
  INDEX `fk_reservation_room_type1_idx` (`room_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_reservation_guest1`
    FOREIGN KEY (`guest_id`)
    REFERENCES `virginia`.`guest` (`guest_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reservation_room_type1`
    FOREIGN KEY (`room_type_id`)
    REFERENCES `virginia`.`room_type` (`room_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virginia`.`room`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virginia`.`room` (
  `room_id` INT NOT NULL,
  `room_name` VARCHAR(100) NOT NULL,
  `room_status` INT(11) NOT NULL,
  `room_type_id` INT NOT NULL,
  `reservation_key` INT NULL,
  PRIMARY KEY (`room_id`),
  INDEX `fk_room_room_type1_idx` (`room_type_id` ASC) VISIBLE,
  CONSTRAINT `fk_room_room_type1`
    FOREIGN KEY (`room_type_id`)
    REFERENCES `virginia`.`room_type` (`room_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `virginia`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `virginia`.`settings` (
  `settings_id` INT NOT NULL AUTO_INCREMENT,
  `settings_tax` INT(10) NOT NULL,
  PRIMARY KEY (`settings_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
